server {
    listen 8080 default_server;
    server_name _;

    if ($host = www.twinn.live) {
        return 301 https://twinn.live$request_uri;
    }

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}